### ISSUE TITLE
Formio Resource Provider Documentation

### ISSUE THREAD

**Issue by jmarkinman** [formio/ngFormioHelper#29]
Hi, I can't seem to find any clear documentation on config(FormioResourceProvider). I'm trying to figure out when to use FormioResourceProvider vs. when to use FormioProvider, the difference between how they work and when and why it is best to use one over the other as well as their configuration details. [Adding documentation here](https://github.com/formio/ngFormioHelper/wiki/FormioResource-Provider) could go a long way to clarify my questions.

Thank You!

**Comment by padhumailin** [comment]
Can you provide the helper for Angular 6 and above
